listr2/listr2

- CHANGELOG.md
- README.md
* **figures:** made microsoft icons to use the fancy ones, even though it may fail in some cases ([f0e5817](https://github.com/cenk1cenk2/listr2/commit/f0e581706e59d9b96da9bd050a1ad3638b59c2aa)), closes [#31](https://github.com/cenk1cenk2/listr2/issues/31)
* **renderer:** added hook and stdout support ([bd73c68](https://github.com/cenk1cenk2/listr2/commit/bd73c68b9eb21cd100a266ce05ba36af0c727a4f)), closes [#31](https://github.com/cenk1cenk2/listr2/issues/31)
> chore(release): 2.1.0-beta.1 - 20200525 [skip ci]

- CHANGELOG.md
- src/renderer/verbose.renderer.ts
- tests/task-skip.e2e-spec.ts
Previously the verbose output would only include the skip output if one called the task.skip. However in our cli we use the skip method and it returns a string. Since this is covered in the default renderer, it seems this use case was missing in the verbose.
> fix(renderer): add skip to verbose output

- CHANGELOG.md
- README.md
- src/utils/logger.ts
So I noticed in our CI after moving to listr2 that skip causes our builds to fail. This is because skip calls `console.warn`, which is an alias for `console.error` 😬. 
I considered writing a custom logger but that proved to be a bit harder since we rely on default behavior of using the default renderer when TTY is enabled and verbose when not. Which causes issues with TS.
> Logger updates

- src/renderer/default.renderer.ts
On `conhost.exe`, these characters were not supported. But on Windows Terminal, they are. The Windows Terminal adds the [`WT_SESSION`](https://github.com/microsoft/terminal/issues/840) environment variable, which allows to identify when it's used. Thanks to that, we can now display fancy figures on Windows. 
This change updates the previous behavior by adding an additional check against the `WT_SESSION` environment variable, in order to allow these characters on the Windows Terminal.
Sources:
- https://github.com/microsoft/terminal/issues/840
Related:
- https://github.com/sindresorhus/elegant-spinner/pull/5
- https://github.com/sindresorhus/log-symbols/pull/24
- https://github.com/sindresorhus/figures/pull/34
> feat: display elegant spinner on Windows Terminal

- README.md
- src/renderer/default.renderer.ts
This adds the flag `persistentErrorOutput` to the task options and closes #137
> Add flag for displaying output even if task errors

- README.md
- examples/get-user-input.example.ts
- src/interfaces/listr.interface.ts
- src/lib/task-wrapper.ts
- src/lib/task.ts
- src/utils/prompt.interface.ts
- src/utils/prompt.ts
This adds functionality for `cancelPrompt` that can exposed to the task itself
There's currently a bug with using multiple prompts when reusing `task.prompt`
@cenk1cenk2 can you take a look at this?
Closes #177
> Add prompt cancel

- src/renderer/default.renderer.ts
- src/utils/prompt.ts
- tsconfig.json
This PR begins to _tighten up_ some of the ts compiler settings. It is purely a change to type information, and should not have any impact on the build output.
> Enable tsconfig `strict` and `noImplicitAny` flags

- etc/listr2.api.md
I forgot to commit the most up-to-date public API surface report in #358. Here's a new file.
These can be regenerated at any time by running
```sh
yarn api-extractor run --local
```
> Update public API surface report

- src/renderer/default.renderer.ts
- src/utils/is-unicode-supported.ts
Currently, Listr only uses the elegant spinners on Windows on the Windows Terminal.
This commits adds another environments that are known to have support for unicode characters and thus, the elegant spinners. 
The initial idea was to simply use [is-unicode-supported](https://github.com/sindresorhus/is-unicode-supported). However, that package doesn't really fits this package's build because v1.0.0 is shipped only as ESM and v0.1.0 would require allowSyntheticDefaultImports or esModuleInterop, which has been removed in this package's config.
Given this situation, I pretty much added a function exactly like sindresorhus' until there's a solution to use the proper package. I will look into open a PR for adding support for no module interop in is-unicode-supported, but I think it's worth …
> feat: use elegant spinner on environments that support unicode

- src/interfaces/listr.interface.ts
- src/lib/task.ts
- tests/__snapshots__/renderer-prompt.e2e-spec.ts.snap
- tests/task-skip.e2e-spec.ts
Closes #411 
Changed the `Promise<boolean> | Promise<string>` -> `Promise<boolean | string>` and provided some tests for variations.
> Allow async skip boolean or string

- .eslintrc.js
- src/interfaces/listr-error.interface.ts
- src/interfaces/listr.interface.ts
- src/lib/task-wrapper.ts
- src/listr.ts
- src/renderer/default.renderer.ts
- tests/error-collection.e2e-spec.ts
I ran into the same(?) issue as #600 and found that commenting out https://github.com/cenk1cenk2/listr2/blob/master/src/lib/task-wrapper.ts#L58 fixed it based on the comments in the issue.
Closes #600(?)
> Add Option to Disable Error Collection

- src/utils/prompt.interface.ts
See https://github.com/enquirer/enquirer#arrayprompt
This option is available for all array prompts.
Some examples: https://github.com/enquirer/enquirer/blob/master/examples/multiselect/option-hint.js, https://github.com/enquirer/enquirer/blob/master/examples/sort/prompt.js
> fix(enquirer): Add hint attr for array prompts

- src/lib/task.ts
Using `instanceof Observable` can fail in cases where the observables come from two different copies of `rxjs` that might be installed in your node_modules. When this condition fails, it causes the task to immediately complete as if it were successful.
> fix: Use 'isObservable' utility instance of 'instanceof'

- package.json
TL;DR: Allows tooling to perform ad-hoc dependency analysis using require.resolve.
Would you be open to exporting the `package.json`.  We have a bunch of tooling that does dependency graph analysis of our packages and there currently isn't a workaround for [non-ESM packages](https://github.com/nodejs/node/issues/33460#issuecomment-630452758).
> feat(package): export the package.json

- docs/format.md
- docs/listr/context.md
- docs/listr/listr.md
- docs/listr/manager.md
- docs/renderer/custom.md
- docs/renderer/default.md
- docs/renderer/fallback-condition.md
- docs/renderer/logger.md
- docs/renderer/process-output.md
- docs/renderer/simple.md
- docs/renderer/test.md
- docs/renderer/verbose.md
- docs/repository/contributions.md
- docs/task/error-handling.md
- docs/task/retry.md
- docs/task/skip.md
- docs/task/task-options.md
- docs/task/task.md
Currently the documentation has many imports that result in empty Options toggles on the documentation website (e.g. https://listr2.kilic.dev/renderer/default.html) which seems to have resulted from typedoc not generating files with a type prefix anymore.
I tried to find all occurances of imports where the paths would be incorrect and hopefully fixed them.
I cannot remember what the docs initially looked like, but attached a screenshot of what the expanded options looks like now. Probably not idea but the best temporary solution for now if you want to keep dev frustration down from having to somehow try and figure out what the class options are.
> Docs: remove file prefix when importing in markdown

- packages/listr2/src/listr.ts
- packages/listr2/tests/signal-handler.e2e-spec.ts
Closes #709 
This PR fixes the problem where Listr is removing all `SIGINT` listeners, instead of just the listeners it manages. I added a "should not clear other SIGINT listeners" test and verified it failed prior to implementing the fix. Now the test passes.
> Fix issues with adding/removing SIGINT listeners

- examples/task-output.example.ts
Removed duplicate example: "Example long multiline output with task with persistent output and wrap." / "Example long multiline output with task with persistent output and word wrap."
> Removed duplicate example in task-output.example.ts

- packages/listr2/src/listr.ts
initialize a listr instance, and **don't** call `run`, press `CTRL+C` will throw exception like this:
```shell
? 💬 ^C2286 |       if (task.isPending()) {
2287 |         task.state$ = "FAILED" /* FAILED */;
2288 |       }
2289 |     });
2290 |     if (this.isRoot()) {
2291 |       this.renderer.end(new Error("Interrupted."));
^
TypeError: undefined is not an object (evaluating 'this.renderer.end')
```
so we need to ignore renderer if it not defined
> fix: renderer maybe undefined

- packages/listr2/src/listr.ts
getRenderer relies on process.stdout.isTTY to determine the renderer.
Previously, the environment variable logic (e.g., forceTTY) was set after calling getRenderer, which could lead to incorrect renderer selection.
This change moves the environment variable setup before getRenderer to ensure the correct renderer is chosen.
> fix: set TTY env before getRenderer

- examples/docs/renderer/process-output/change-behavior.ts
The `stdout` and `stderr` parameters for the `ProcessOutput` constructor take in `NodeJS.WriteStream | undefined`, so passing in `null` as the current example does throws the following TypeScript error:
```
Argument of type 'null' is not assignable to parameter of type 'WriteStream | undefined'.ts(2345)
```
https://github.com/listr2/listr2/blob/1e57e090dacd904ea259d8c1518c8bdb91ba3ff1/packages/listr2/src/utils/process-output/process-output.ts#L20-L21
> docs: fix types in `process-output/change-behavior` example

- packages/prompt-adapter-enquirer/package.json
- packages/prompt-adapter-inquirer/package.json
Since `listr2` is required at runtime, it should be declared as a peer dependency.
> fix: list `listr2` as a peer dependency
